AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Catalog: EC2 Reference Architecture(fdp-1oc5f3ula).'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - KeyPair
      - Label:
          default: Linux Instance Configuration
        Parameters:
          - LinuxInstanceType
          - LinuxSubnetPrivacy
          - LinuxSSHPort
          - LatestAmiId
    ParameterLabels:
      KeyPair:
        default: Key Pair
      LinuxInstanceType:
        default: Linux Instance Type
      LinuxSubnetPrivacy:
        default: Linux Subnet Privacy
      LinuxSSHPort:
        default: Linux SSH Port
      LatestAmiId:
        default: SSM key to the latest Amazon linux AMI
Parameters:
  LinuxSubnetPrivacy:
    Type: AWS::EC2::Subnet::Id
    Description: Select a public or private subnet
    AllowedValues:
      - private
      - public
    Default: private
  LinuxInstanceType:
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    Default: t3.micro
    Description: Amazon EC2 Linux Instance Type
    Type: String
  LinuxSSHPort:
    Description: Linux SSH Port Number
    Type: Number
    Default: 22
    ConstraintDescription: must be 22 or a number from 1024 to 65535
  KeyPair:
    Description: Name of existing EC2 key pair for Linux Instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: scipool
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
Conditions:
  HasPublicSubnet: !Equals
    - !Ref LinuxSubnetPrivacy
    - public
Resources:
  InstancePatchingRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
  PatchingInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref 'InstancePatchingRole'
  LinuxInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref 'LatestAmiId'
      InstanceType: !Ref 'LinuxInstanceType'
      SubnetId:
        !If
        - HasPublicSubnet
        - !Sub '${AWS::Region}-sc-vpc-ra-SubnetAPublicID'
        - !Sub '${AWS::Region}-sc-vpc-ra-SubnetAPrivateID'
      SecurityGroupIds:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-sc-vpc-ra-VPNSecurityGroupID'
      KeyName: !Ref 'KeyPair'
      IamInstanceProfile: !Ref 'PatchingInstanceProfile'
      Tags:
        - Key: Description
          Value: Service-Catalog-EC2-Reference-Architecture
  LinuxPatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      OperatingSystem: AMAZON_LINUX
      ApprovalRules:
        PatchRules:
          - ApproveAfterDays: 0
            ComplianceLevel: CRITICAL
            EnableNonSecurity: true
            PatchFilterGroup:
              PatchFilters:
                - Key: PRODUCT
                  Values:
                    - '*'
                - Key: CLASSIFICATION
                  Values:
                    - Security
                    - Bugfix
                    - Enhancement
                    - Recommended
                - Key: SEVERITY
                  Values:
                    - Critical
                    - Important
                    - Medium
                    - Low
      Description: Service Catalog EC2 Reference Architecture Patch Baseline for Amazon
        Linux instace
      Name: sc-ec2-ra-linux-patch-baseline
  MaintenanceWindowRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
  MaintenanceWindow:
    Type: AWS::SSM::MaintenanceWindow
    Properties:
      Description: Maintenance window to allow for patching Amazon Linux instances
      AllowUnassociatedTargets: false
      Cutoff: 2
      Schedule: cron(* 17 * * ? *)
      Duration: 6
      Name: sc-ec2-ra-linux-maintenance-window
  LinuxMainteanceWindowTarget:
    Type: AWS::SSM::MaintenanceWindowTarget
    Properties:
      OwnerInformation: Service Catalog EC2 Reference Architecture
      Description: Service Catalog EC2 Reference Architecture - Patch Maintenance
        for Amazon Linux Instances
      WindowId: !Ref 'MaintenanceWindow'
      ResourceType: INSTANCE
      Targets:
        - Key: InstanceIds
          Values:
            - !Ref 'LinuxInstance'
      Name: sc-ec2-ra-linux-patch-targets
  LinuxMaintenanceWindowTaskScan:
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      MaxErrors: 1
      Description: 'Service Catalog EC2 Reference Architecture Maintenance Window
        Task: Scan for update for Amazon Linux Instance'
      ServiceRoleArn: !GetAtt 'MaintenanceWindowRole.Arn'
      Priority: 1
      MaxConcurrency: 1
      Targets:
        - Key: InstanceIds
          Values:
            - !Ref 'LinuxInstance'
      Name: patch-sc-ec2-ra-linux-instances
      TaskArn: AWS-RunPatchBaseline
      WindowId: !Ref 'MaintenanceWindow'
      TaskParameters:
        Operation:
          Values:
            - Scan
      TaskType: RUN_COMMAND
  LinuxMaintenanceWindowTaskInstall:
    Type: AWS::SSM::MaintenanceWindowTask
    Properties:
      MaxErrors: 1
      Description: 'Service Catalog EC2 Reference Architecture Maintenance Window
        Task: Install update for Amazon Linux Instance'
      ServiceRoleArn: !GetAtt 'MaintenanceWindowRole.Arn'
      Priority: 2
      MaxConcurrency: 1
      Targets:
        - Key: InstanceIds
          Values:
            - !Ref 'LinuxInstance'
      Name: patch-sc-ec2-ra-linux-instances
      TaskArn: AWS-RunPatchBaseline
      WindowId: !Ref 'MaintenanceWindow'
      TaskParameters:
        Operation:
          Values:
            - Install
      TaskType: RUN_COMMAND
Outputs:
  TemplateID:
    Value: service-catalog-reference-architectures/sc-ec2-ra
  AWSRegionName:
    Value: !Ref 'AWS::Region'
  LinuxInstanceId:
    Value: !Ref 'LinuxInstance'
  LinuxInstancePrivateIpAddress:
    Value: !GetAtt 'LinuxInstance.PrivateIp'
  LinuxInstanceAvailabilityZone:
    Value: !GetAtt 'LinuxInstance.AvailabilityZone'
  KeyPair:
    Value: !Ref 'KeyPair'
  LinuxSSHPort:
    Value: !Ref 'LinuxSSHPort'
  LinuxInstanceType:
    Value: !Ref 'LinuxInstanceType'
  RemoteAccessCIDR:
    Value: !Ref 'RemoteAccessCIDR'
  VPC:
    Value: !Ref 'VPC'
  IAMInstancePatchingRole:
    Value: !Ref 'InstancePatchingRole'
  IAMPatchingInstanceProfile:
    Value: !Ref 'PatchingInstanceProfile'
  SSMMaintenaceWindowRole:
    Value: !Ref 'MaintenanceWindowRole'
  SSMLinuxPatchBaseline:
    Value: !Ref 'LinuxPatchBaseline'
