AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service Catalog: S3 Reference Architecture: Public read-only bucket accessible from anywhere.Consider alternate options like distributing via CloudFront OAI instead of creating bucket using this template.(fdp-1oc5gsre6). Review IAM permissions, Deletion policies, update stack behavior, other aspects of the template, and ensure that they are as per your expectations and processes. Sample CloudFormation templates may need updates before you can use them. Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.Licensed under the Apache License, Version 2.0 (the \"License\"). You may not use this file except in compliance with the License.A copy of the License is located at http://www.apache.org/licenses/LICENSE-2.0 or in the \"license\" file accompanying this file. This file is distributed on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      Tags:
      - Key: Name
        Value: SC-S3-RA-S3-Bucket
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the Amazon S3 bucket.
  BucketARN:
    Value: !GetAtt S3Bucket.Arn
