version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - sudo apt-get install zip gzip tar -y
      - pip3 install --upgrade pip
      - pip install taskcat    
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - cp ec2/*.json templates/
      - export dirname=${PWD##*/}
      - echo Directory name $dirname
      - cd ..
      - mv $dirname $PROJECTNAME
      - echo Configuring aws cli...
      - aws configure set default.region us-east-1
  build:
    commands:
      - echo Entered the build phase...
      - taskcat -c $PROJECTNAME/ci/taskcat.yml
      - echo uploading report to $ARTIFACT_BUCKET S3 bucket
      - aws s3 sync taskcat_outputs s3://$ARTIFACT_BUCKET/taskcat_reports/$CODEBUILD_BUILD_ID
      - |
        if $(grep -Fq "CREATE_FAILED" taskcat_outputs/index.html)
        then
          echo Quickstart FAILED!
          exit 1
        else
          echo Quickstart Passed!
          exit 0
        fi
